version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      - cd cdk
      - npm install -g aws-cdk
      - python -m pip install -r requirements.txt
  build:
    commands:
      - cdk diff
  post_build:
    commands:
      - echo Build completed on `date`
