projects:
  examplegraphqlapi:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        region: <region>
        apiId: <appsyncid>
        maxDepth: 2
extensions:
  amplify:
    version: 3
