version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - cd webapp
      - npm install
  build:
    commands:
      - npm run-script build
  post_build:
    commands:
      - aws s3 sync ./build/ s3://example-webapp/
      - echo Build completed on `date`
artifacts:
  files:
    - build